version: '3.8'

services:
  ota-server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    env_file:
      - .env
    command: reflex -r '\.go' -s -- sh -c "ls -l cmd/api && go run cmd/api/main.go"
