// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID                         int64              `json:"id"`
	AppID                      pgtype.UUID        `json:"app_id"`
	Name                       string             `json:"name"`
	Hint                       string             `json:"hint"`
	HashedKey                  string             `json:"hashed_key"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt                 pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt                  pgtype.Timestamptz `json:"revoked_at"`
	AllowedIps                 []netip.Prefix     `json:"allowed_ips"`
	CanAccessProtectedBranches bool               `json:"can_access_protected_branches"`
}

type App struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	KeysMode           *string            `json:"keys_mode"`
	SealedPublicKey    *string            `json:"sealed_public_key"`
	SealedPrivateKey   *string            `json:"sealed_private_key"`
	PathPublicKey      *string            `json:"path_public_key"`
	PathPrivateKey     *string            `json:"path_private_key"`
	AwsSecretIDPublic  *string            `json:"aws_secret_id_public"`
	AwsSecretIDPrivate *string            `json:"aws_secret_id_private"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Branch struct {
	ID        int64              `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Protected bool               `json:"protected"`
}

type Channel struct {
	ID        int64              `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	BranchID  *int64             `json:"branch_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EnterpriseLicense struct {
	Singleton  bool               `json:"singleton"`
	LicenseKey string             `json:"license_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type RuntimeVersion struct {
	ID        int64              `json:"id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Version   string             `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SsoConfig struct {
	Singleton            bool               `json:"singleton"`
	Issuer               string             `json:"issuer"`
	ClientID             string             `json:"client_id"`
	SealedClientSecret   string             `json:"sealed_client_secret"`
	ProviderName         string             `json:"provider_name"`
	Scopes               string             `json:"scopes"`
	Enabled              bool               `json:"enabled"`
	AllowedEmailDomains  []string           `json:"allowed_email_domains"`
	AllowedGroups        []string           `json:"allowed_groups"`
	GroupsClaim          string             `json:"groups_claim"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	TrustUnverifiedEmail bool               `json:"trust_unverified_email"`
	ManualUserValidation bool               `json:"manual_user_validation"`
}

type SsoIdentity struct {
	Issuer      string             `json:"issuer"`
	Subject     string             `json:"subject"`
	UserID      pgtype.UUID        `json:"user_id"`
	Email       string             `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

type Update struct {
	ID               int64              `json:"id"`
	UpdateUuid       pgtype.UUID        `json:"update_uuid"`
	BranchID         int64              `json:"branch_id"`
	RuntimeVersionID int64              `json:"runtime_version_id"`
	UpdateType       int32              `json:"update_type"`
	CommitHash       string             `json:"commit_hash"`
	Message          *string            `json:"message"`
	Platform         string             `json:"platform"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CheckedAt        pgtype.Timestamptz `json:"checked_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	IsAdmin         bool               `json:"is_admin"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	LastConnectedAt pgtype.Timestamptz `json:"last_connected_at"`
	Enabled         bool               `json:"enabled"`
}
