// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAppByID = `-- name: DeleteAppByID :execresult
DELETE FROM apps
WHERE id = $1
`

func (q *Queries) DeleteAppByID(ctx context.Context, id pgtype.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteAppByID, id)
}

const deleteBranchByName = `-- name: DeleteBranchByName :execresult
DELETE FROM branches
WHERE name = $1 AND app_id = $2
`

type DeleteBranchByNameParams struct {
	Name  string      `json:"name"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) DeleteBranchByName(ctx context.Context, arg DeleteBranchByNameParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteBranchByName, arg.Name, arg.AppID)
}

const deleteChannelByName = `-- name: DeleteChannelByName :execresult
DELETE FROM channels
WHERE name = $1 AND app_id = $2
`

type DeleteChannelByNameParams struct {
	Name  string      `json:"name"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) DeleteChannelByName(ctx context.Context, arg DeleteChannelByNameParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteChannelByName, arg.Name, arg.AppID)
}

const getApiKeysMetadataByAppID = `-- name: GetApiKeysMetadataByAppID :many
SELECT id, name, hint, created_at, last_used_at
FROM api_keys
WHERE app_id = $1 AND revoked_at IS NULL
ORDER BY created_at ASC
`

type GetApiKeysMetadataByAppIDRow struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Hint       string             `json:"hint"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) GetApiKeysMetadataByAppID(ctx context.Context, appID pgtype.UUID) ([]GetApiKeysMetadataByAppIDRow, error) {
	rows, err := q.db.Query(ctx, getApiKeysMetadataByAppID, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApiKeysMetadataByAppIDRow
	for rows.Next() {
		var i GetApiKeysMetadataByAppIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hint,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppByID = `-- name: GetAppByID :one
SELECT id, name, keys_mode, sealed_public_key, sealed_private_key, path_public_key, path_private_key, aws_secret_id_public, aws_secret_id_private, created_at, updated_at FROM apps
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAppByID(ctx context.Context, id pgtype.UUID) (App, error) {
	row := q.db.QueryRow(ctx, getAppByID, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeysMode,
		&i.SealedPublicKey,
		&i.SealedPrivateKey,
		&i.PathPublicKey,
		&i.PathPrivateKey,
		&i.AwsSecretIDPublic,
		&i.AwsSecretIDPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApps = `-- name: GetApps :many
SELECT id, name 
FROM apps
ORDER BY created_at ASC
`

type GetAppsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) GetApps(ctx context.Context) ([]GetAppsRow, error) {
	rows, err := q.db.Query(ctx, getApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAppsRow
	for rows.Next() {
		var i GetAppsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBranchByName = `-- name: GetBranchByName :one
SELECT id FROM branches
WHERE name = $1 AND app_id = $2
LIMIT 1
`

type GetBranchByNameParams struct {
	Name  string      `json:"name"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) GetBranchByName(ctx context.Context, arg GetBranchByNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, getBranchByName, arg.Name, arg.AppID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getBranchesByAppID = `-- name: GetBranchesByAppID :many
SELECT DISTINCT ON (branches.id) 
    branches.id, branches.app_id, branches.name, branches.created_at, 
    channels.name AS channel_name 
FROM branches
LEFT JOIN channels ON branches.id = channels.branch_id AND channels.app_id = branches.app_id
WHERE branches.app_id = $1
`

type GetBranchesByAppIDRow struct {
	ID          int64              `json:"id"`
	AppID       pgtype.UUID        `json:"app_id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ChannelName *string            `json:"channel_name"`
}

func (q *Queries) GetBranchesByAppID(ctx context.Context, appID pgtype.UUID) ([]GetBranchesByAppIDRow, error) {
	rows, err := q.db.Query(ctx, getBranchesByAppID, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBranchesByAppIDRow
	for rows.Next() {
		var i GetBranchesByAppIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.Name,
			&i.CreatedAt,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelBranchMapping = `-- name: GetChannelBranchMapping :one
SELECT c.id, b.name AS branch_name
FROM channels c
JOIN branches b ON c.branch_id = b.id AND b.app_id = c.app_id
WHERE c.app_id = $1 AND c.name = $2
`

type GetChannelBranchMappingParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Name  string      `json:"name"`
}

type GetChannelBranchMappingRow struct {
	ID         int64  `json:"id"`
	BranchName string `json:"branch_name"`
}

func (q *Queries) GetChannelBranchMapping(ctx context.Context, arg GetChannelBranchMappingParams) (GetChannelBranchMappingRow, error) {
	row := q.db.QueryRow(ctx, getChannelBranchMapping, arg.AppID, arg.Name)
	var i GetChannelBranchMappingRow
	err := row.Scan(&i.ID, &i.BranchName)
	return i, err
}

const getChannelNamesByBranchName = `-- name: GetChannelNamesByBranchName :many
SELECT c.name
FROM channels c
INNER JOIN branches b ON c.branch_id = b.id AND b.app_id = c.app_id
WHERE b.name = $1 AND b.app_id = $2
ORDER BY c.created_at ASC
`

type GetChannelNamesByBranchNameParams struct {
	Name  string      `json:"name"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) GetChannelNamesByBranchName(ctx context.Context, arg GetChannelNamesByBranchNameParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getChannelNamesByBranchName, arg.Name, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelsByAppID = `-- name: GetChannelsByAppID :many
SELECT channels.id, channels.app_id, channels.branch_id, channels.name, channels.created_at, branches.name as branch_name 
FROM channels
LEFT JOIN branches ON channels.branch_id = branches.id AND branches.app_id = channels.app_id
WHERE channels.app_id = $1
ORDER BY channels.created_at ASC
`

type GetChannelsByAppIDRow struct {
	ID         int64              `json:"id"`
	AppID      pgtype.UUID        `json:"app_id"`
	BranchID   *int64             `json:"branch_id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	BranchName *string            `json:"branch_name"`
}

func (q *Queries) GetChannelsByAppID(ctx context.Context, appID pgtype.UUID) ([]GetChannelsByAppIDRow, error) {
	rows, err := q.db.Query(ctx, getChannelsByAppID, appID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelsByAppIDRow
	for rows.Next() {
		var i GetChannelsByAppIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AppID,
			&i.BranchID,
			&i.Name,
			&i.CreatedAt,
			&i.BranchName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestUpdate = `-- name: GetLatestUpdate :one
SELECT 
    u.id,
    u.update_uuid,
    u.branch_id,
    u.runtime_version_id,
    u.update_type,
    u.commit_hash,
    u.message,
    u.platform,
    u.created_at
FROM updates u
JOIN branches b ON u.branch_id = b.id
JOIN runtime_versions rv ON u.runtime_version_id = rv.id
WHERE b.app_id = $1
  AND b.name = $2
  AND rv.version = $3
  AND u.platform = $4
  AND u.checked_at IS NOT NULL
ORDER BY u.id DESC
LIMIT 1
`

type GetLatestUpdateParams struct {
	AppID    pgtype.UUID `json:"app_id"`
	Name     string      `json:"name"`
	Version  string      `json:"version"`
	Platform string      `json:"platform"`
}

type GetLatestUpdateRow struct {
	ID               int64              `json:"id"`
	UpdateUuid       pgtype.UUID        `json:"update_uuid"`
	BranchID         int64              `json:"branch_id"`
	RuntimeVersionID int64              `json:"runtime_version_id"`
	UpdateType       int32              `json:"update_type"`
	CommitHash       string             `json:"commit_hash"`
	Message          *string            `json:"message"`
	Platform         string             `json:"platform"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetLatestUpdate(ctx context.Context, arg GetLatestUpdateParams) (GetLatestUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLatestUpdate,
		arg.AppID,
		arg.Name,
		arg.Version,
		arg.Platform,
	)
	var i GetLatestUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UpdateUuid,
		&i.BranchID,
		&i.RuntimeVersionID,
		&i.UpdateType,
		&i.CommitHash,
		&i.Message,
		&i.Platform,
		&i.CreatedAt,
	)
	return i, err
}

const getRuntimeVersionsWithUpdateCount = `-- name: GetRuntimeVersionsWithUpdateCount :many
SELECT 
    rv.id, 
    rv.version, 
    rv.created_at, 
    rv.updated_at,
    (
        SELECT COUNT(u.id)
        FROM updates u
        JOIN branches b ON u.branch_id = b.id
        WHERE u.runtime_version_id = rv.id 
          AND b.name = $2 AND u.checked_at IS NOT NULL
    ) AS update_count
FROM runtime_versions rv
WHERE rv.app_id = $1
  -- Only allow rows where at least one matching update exists
  AND EXISTS (
      SELECT 1 
      FROM updates u
      JOIN branches b ON u.branch_id = b.id
      WHERE u.runtime_version_id = rv.id 
        AND b.name = $2
        AND u.checked_at IS NOT NULL
  )
ORDER BY rv.created_at DESC
`

type GetRuntimeVersionsWithUpdateCountParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Name  string      `json:"name"`
}

type GetRuntimeVersionsWithUpdateCountRow struct {
	ID          int64              `json:"id"`
	Version     string             `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UpdateCount int64              `json:"update_count"`
}

func (q *Queries) GetRuntimeVersionsWithUpdateCount(ctx context.Context, arg GetRuntimeVersionsWithUpdateCountParams) ([]GetRuntimeVersionsWithUpdateCountRow, error) {
	rows, err := q.db.Query(ctx, getRuntimeVersionsWithUpdateCount, arg.AppID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRuntimeVersionsWithUpdateCountRow
	for rows.Next() {
		var i GetRuntimeVersionsWithUpdateCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdateCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdateByBranchNameAndRuntime = `-- name: GetUpdateByBranchNameAndRuntime :one
SELECT u.id, u.update_uuid, b.app_id, b.name AS branch_name, r.version AS runtime_version, u.update_type, u.commit_hash, u.message, u.platform, u.created_at
FROM updates u
INNER JOIN branches b ON u.branch_id = b.id
INNER JOIN runtime_versions r ON u.runtime_version_id = r.id
WHERE b.app_id = $1
  AND u.id = $2
  AND b.name = $3
  AND r.version = $4
LIMIT 1
`

type GetUpdateByBranchNameAndRuntimeParams struct {
	AppID   pgtype.UUID `json:"app_id"`
	ID      int64       `json:"id"`
	Name    string      `json:"name"`
	Version string      `json:"version"`
}

type GetUpdateByBranchNameAndRuntimeRow struct {
	ID             int64              `json:"id"`
	UpdateUuid     pgtype.UUID        `json:"update_uuid"`
	AppID          pgtype.UUID        `json:"app_id"`
	BranchName     string             `json:"branch_name"`
	RuntimeVersion string             `json:"runtime_version"`
	UpdateType     int32              `json:"update_type"`
	CommitHash     string             `json:"commit_hash"`
	Message        *string            `json:"message"`
	Platform       string             `json:"platform"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// app_id is load-bearing, not redundant: pk_updates is (branch_id, id), so an
// update id is only unique per branch, and branch names are only unique per app.
// Without the app filter the same (id, branch, runtime) triple matches another
// tenant's row.
func (q *Queries) GetUpdateByBranchNameAndRuntime(ctx context.Context, arg GetUpdateByBranchNameAndRuntimeParams) (GetUpdateByBranchNameAndRuntimeRow, error) {
	row := q.db.QueryRow(ctx, getUpdateByBranchNameAndRuntime,
		arg.AppID,
		arg.ID,
		arg.Name,
		arg.Version,
	)
	var i GetUpdateByBranchNameAndRuntimeRow
	err := row.Scan(
		&i.ID,
		&i.UpdateUuid,
		&i.AppID,
		&i.BranchName,
		&i.RuntimeVersion,
		&i.UpdateType,
		&i.CommitHash,
		&i.Message,
		&i.Platform,
		&i.CreatedAt,
	)
	return i, err
}

const getUpdateCheckedAt = `-- name: GetUpdateCheckedAt :one
SELECT u.checked_at
FROM updates u
JOIN branches b ON u.branch_id = b.id
WHERE b.app_id = $1
  AND b.name = $2
  AND u.id = $3
`

type GetUpdateCheckedAtParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Name  string      `json:"name"`
	ID    int64       `json:"id"`
}

func (q *Queries) GetUpdateCheckedAt(ctx context.Context, arg GetUpdateCheckedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getUpdateCheckedAt, arg.AppID, arg.Name, arg.ID)
	var checked_at pgtype.Timestamptz
	err := row.Scan(&checked_at)
	return checked_at, err
}

const getUpdateMetadata = `-- name: GetUpdateMetadata :one
SELECT updates.id, update_uuid, platform, commit_hash, message
FROM updates
JOIN branches ON updates.branch_id = branches.id
WHERE branches.app_id = $2
  AND branches.name = $3
  AND updates.id = $1
`

type GetUpdateMetadataParams struct {
	ID    int64       `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
	Name  string      `json:"name"`
}

type GetUpdateMetadataRow struct {
	ID         int64       `json:"id"`
	UpdateUuid pgtype.UUID `json:"update_uuid"`
	Platform   string      `json:"platform"`
	CommitHash string      `json:"commit_hash"`
	Message    *string     `json:"message"`
}

func (q *Queries) GetUpdateMetadata(ctx context.Context, arg GetUpdateMetadataParams) (GetUpdateMetadataRow, error) {
	row := q.db.QueryRow(ctx, getUpdateMetadata, arg.ID, arg.AppID, arg.Name)
	var i GetUpdateMetadataRow
	err := row.Scan(
		&i.ID,
		&i.UpdateUuid,
		&i.Platform,
		&i.CommitHash,
		&i.Message,
	)
	return i, err
}

const getUpdateType = `-- name: GetUpdateType :one
SELECT u.update_type 
FROM updates u
JOIN branches b ON u.branch_id = b.id
WHERE b.app_id = $1
  AND b.name = $2
  AND u.id = $3
`

type GetUpdateTypeParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Name  string      `json:"name"`
	ID    int64       `json:"id"`
}

func (q *Queries) GetUpdateType(ctx context.Context, arg GetUpdateTypeParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUpdateType, arg.AppID, arg.Name, arg.ID)
	var update_type int32
	err := row.Scan(&update_type)
	return update_type, err
}

const getUpdatesByByBranchNameAndRuntimeVersion = `-- name: GetUpdatesByByBranchNameAndRuntimeVersion :many
SELECT u.id, u.update_uuid, u.update_type, u.created_at, u.commit_hash, u.platform, u.message, u.checked_at
FROM updates u
JOIN runtime_versions rv ON u.runtime_version_id = rv.id
JOIN branches b ON u.branch_id = b.id
JOIN apps a ON b.app_id = a.id
WHERE a.id = $1 
  AND rv.version = $2 
  AND b.name = $3
  AND u.checked_at IS NOT NULL
ORDER BY u.created_at DESC
`

type GetUpdatesByByBranchNameAndRuntimeVersionParams struct {
	ID      pgtype.UUID `json:"id"`
	Version string      `json:"version"`
	Name    string      `json:"name"`
}

type GetUpdatesByByBranchNameAndRuntimeVersionRow struct {
	ID         int64              `json:"id"`
	UpdateUuid pgtype.UUID        `json:"update_uuid"`
	UpdateType int32              `json:"update_type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CommitHash string             `json:"commit_hash"`
	Platform   string             `json:"platform"`
	Message    *string            `json:"message"`
	CheckedAt  pgtype.Timestamptz `json:"checked_at"`
}

func (q *Queries) GetUpdatesByByBranchNameAndRuntimeVersion(ctx context.Context, arg GetUpdatesByByBranchNameAndRuntimeVersionParams) ([]GetUpdatesByByBranchNameAndRuntimeVersionRow, error) {
	rows, err := q.db.Query(ctx, getUpdatesByByBranchNameAndRuntimeVersion, arg.ID, arg.Version, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpdatesByByBranchNameAndRuntimeVersionRow
	for rows.Next() {
		var i GetUpdatesByByBranchNameAndRuntimeVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.UpdateUuid,
			&i.UpdateType,
			&i.CreatedAt,
			&i.CommitHash,
			&i.Platform,
			&i.Message,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdatesMetadataByBranchName = `-- name: GetUpdatesMetadataByBranchName :many
SELECT u.id, rv.version AS runtime_version
FROM updates u
INNER JOIN branches b ON u.branch_id = b.id
INNER JOIN runtime_versions rv ON u.runtime_version_id = rv.id
WHERE b.name = $1 AND b.app_id = $2
`

type GetUpdatesMetadataByBranchNameParams struct {
	Name  string      `json:"name"`
	AppID pgtype.UUID `json:"app_id"`
}

type GetUpdatesMetadataByBranchNameRow struct {
	ID             int64  `json:"id"`
	RuntimeVersion string `json:"runtime_version"`
}

func (q *Queries) GetUpdatesMetadataByBranchName(ctx context.Context, arg GetUpdatesMetadataByBranchNameParams) ([]GetUpdatesMetadataByBranchNameRow, error) {
	rows, err := q.db.Query(ctx, getUpdatesMetadataByBranchName, arg.Name, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpdatesMetadataByBranchNameRow
	for rows.Next() {
		var i GetUpdatesMetadataByBranchNameRow
		if err := rows.Scan(&i.ID, &i.RuntimeVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertApiKey = `-- name: InsertApiKey :exec
INSERT INTO api_keys (app_id, name, hint, hashed_key)
VALUES ($1, $2, $3, $4)
`

type InsertApiKeyParams struct {
	AppID     pgtype.UUID `json:"app_id"`
	Name      string      `json:"name"`
	Hint      string      `json:"hint"`
	HashedKey string      `json:"hashed_key"`
}

func (q *Queries) InsertApiKey(ctx context.Context, arg InsertApiKeyParams) error {
	_, err := q.db.Exec(ctx, insertApiKey,
		arg.AppID,
		arg.Name,
		arg.Hint,
		arg.HashedKey,
	)
	return err
}

const insertApp = `-- name: InsertApp :one
INSERT INTO apps (id, name, keys_mode, sealed_public_key, sealed_private_key, path_public_key, path_private_key, aws_secret_id_public, aws_secret_id_private)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertAppParams struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	KeysMode           *string     `json:"keys_mode"`
	SealedPublicKey    *string     `json:"sealed_public_key"`
	SealedPrivateKey   *string     `json:"sealed_private_key"`
	PathPublicKey      *string     `json:"path_public_key"`
	PathPrivateKey     *string     `json:"path_private_key"`
	AwsSecretIDPublic  *string     `json:"aws_secret_id_public"`
	AwsSecretIDPrivate *string     `json:"aws_secret_id_private"`
}

func (q *Queries) InsertApp(ctx context.Context, arg InsertAppParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertApp,
		arg.ID,
		arg.Name,
		arg.KeysMode,
		arg.SealedPublicKey,
		arg.SealedPrivateKey,
		arg.PathPublicKey,
		arg.PathPrivateKey,
		arg.AwsSecretIDPublic,
		arg.AwsSecretIDPrivate,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertBranch = `-- name: InsertBranch :one
INSERT INTO branches (app_id, name)
VALUES ($1, $2)
RETURNING id
`

type InsertBranchParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Name  string      `json:"name"`
}

func (q *Queries) InsertBranch(ctx context.Context, arg InsertBranchParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBranch, arg.AppID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChannel = `-- name: InsertChannel :one
INSERT INTO channels (app_id, branch_id, name)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertChannelParams struct {
	AppID    pgtype.UUID `json:"app_id"`
	BranchID *int64      `json:"branch_id"`
	Name     string      `json:"name"`
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChannel, arg.AppID, arg.BranchID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertRuntimeVersion = `-- name: InsertRuntimeVersion :one
INSERT INTO runtime_versions (app_id, version)
VALUES ($1, $2)
RETURNING id
`

type InsertRuntimeVersionParams struct {
	AppID   pgtype.UUID `json:"app_id"`
	Version string      `json:"version"`
}

func (q *Queries) InsertRuntimeVersion(ctx context.Context, arg InsertRuntimeVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertRuntimeVersion, arg.AppID, arg.Version)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertUpdate = `-- name: InsertUpdate :one
WITH resolved_names AS (
    SELECT 
        b.id AS resolved_branch_id,
        rv.id AS resolved_runtime_version_id,
        b.app_id,
        b.name AS branch_name,
        rv.version AS runtime_version
    FROM branches b
    INNER JOIN runtime_versions rv ON rv.app_id = b.app_id
    WHERE b.name = $2
      AND rv.version = $4
      AND b.app_id = $3
)
INSERT INTO updates (
    id, 
    branch_id, 
    runtime_version_id, 
    update_type, 
    platform, 
    commit_hash, 
    message
) VALUES (
    $1,
    (SELECT resolved_branch_id FROM resolved_names),
    (SELECT resolved_runtime_version_id FROM resolved_names),
    $5,
    $6,
    $7,
    $8
)
RETURNING 
    id, 
    platform, 
    commit_hash, 
    message, 
    created_at,
    (SELECT app_id FROM resolved_names) AS app_id,
    (SELECT branch_name FROM resolved_names) AS branch_name,
    (SELECT runtime_version FROM resolved_names) AS runtime_version
`

type InsertUpdateParams struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	AppID      pgtype.UUID `json:"app_id"`
	Version    string      `json:"version"`
	UpdateType int32       `json:"update_type"`
	Platform   string      `json:"platform"`
	CommitHash string      `json:"commit_hash"`
	Message    *string     `json:"message"`
}

type InsertUpdateRow struct {
	ID             int64              `json:"id"`
	Platform       string             `json:"platform"`
	CommitHash     string             `json:"commit_hash"`
	Message        *string            `json:"message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AppID          pgtype.UUID        `json:"app_id"`
	BranchName     string             `json:"branch_name"`
	RuntimeVersion string             `json:"runtime_version"`
}

func (q *Queries) InsertUpdate(ctx context.Context, arg InsertUpdateParams) (InsertUpdateRow, error) {
	row := q.db.QueryRow(ctx, insertUpdate,
		arg.ID,
		arg.Name,
		arg.AppID,
		arg.Version,
		arg.UpdateType,
		arg.Platform,
		arg.CommitHash,
		arg.Message,
	)
	var i InsertUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.CommitHash,
		&i.Message,
		&i.CreatedAt,
		&i.AppID,
		&i.BranchName,
		&i.RuntimeVersion,
	)
	return i, err
}

const markUpdateAsChecked = `-- name: MarkUpdateAsChecked :exec
WITH updated_rows AS (
    UPDATE updates
    SET checked_at = CURRENT_TIMESTAMP
    WHERE updates.id = $1
      AND updates.branch_id = (
          SELECT branches.id 
          FROM branches 
          WHERE branches.app_id = $2
            AND branches.name = $3
      )
    RETURNING runtime_version_id
)
UPDATE runtime_versions
SET updated_at = CURRENT_TIMESTAMP
WHERE id = (SELECT runtime_version_id FROM updated_rows)
`

type MarkUpdateAsCheckedParams struct {
	ID    int64       `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
	Name  string      `json:"name"`
}

func (q *Queries) MarkUpdateAsChecked(ctx context.Context, arg MarkUpdateAsCheckedParams) error {
	_, err := q.db.Exec(ctx, markUpdateAsChecked, arg.ID, arg.AppID, arg.Name)
	return err
}

const migrateLegacyApp = `-- name: MigrateLegacyApp :exec
INSERT INTO apps (
    id, 
    name, 
    keys_mode, 
    sealed_public_key, 
    sealed_private_key, 
    path_public_key, 
    path_private_key, 
    aws_secret_id_public, 
    aws_secret_id_private
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    keys_mode = EXCLUDED.keys_mode,
    sealed_public_key = EXCLUDED.sealed_public_key,
    sealed_private_key = EXCLUDED.sealed_private_key,
    path_public_key = EXCLUDED.path_public_key,
    path_private_key = EXCLUDED.path_private_key,
    aws_secret_id_public = EXCLUDED.aws_secret_id_public,
    aws_secret_id_private = EXCLUDED.aws_secret_id_private
`

type MigrateLegacyAppParams struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	KeysMode           *string     `json:"keys_mode"`
	SealedPublicKey    *string     `json:"sealed_public_key"`
	SealedPrivateKey   *string     `json:"sealed_private_key"`
	PathPublicKey      *string     `json:"path_public_key"`
	PathPrivateKey     *string     `json:"path_private_key"`
	AwsSecretIDPublic  *string     `json:"aws_secret_id_public"`
	AwsSecretIDPrivate *string     `json:"aws_secret_id_private"`
}

func (q *Queries) MigrateLegacyApp(ctx context.Context, arg MigrateLegacyAppParams) error {
	_, err := q.db.Exec(ctx, migrateLegacyApp,
		arg.ID,
		arg.Name,
		arg.KeysMode,
		arg.SealedPublicKey,
		arg.SealedPrivateKey,
		arg.PathPublicKey,
		arg.PathPrivateKey,
		arg.AwsSecretIDPublic,
		arg.AwsSecretIDPrivate,
	)
	return err
}

const migrateLegacyBranch = `-- name: MigrateLegacyBranch :one
INSERT INTO branches (
    app_id, 
    name
) VALUES (
    $1, 
    $2
)
ON CONFLICT (app_id, name) DO UPDATE SET
    name = EXCLUDED.name
RETURNING id
`

type MigrateLegacyBranchParams struct {
	AppID pgtype.UUID `json:"app_id"`
	Name  string      `json:"name"`
}

func (q *Queries) MigrateLegacyBranch(ctx context.Context, arg MigrateLegacyBranchParams) (int64, error) {
	row := q.db.QueryRow(ctx, migrateLegacyBranch, arg.AppID, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const migrateLegacyChannel = `-- name: MigrateLegacyChannel :exec
INSERT INTO channels (
    app_id, 
    branch_id, 
    name
) VALUES (
    $1, 
    $2, 
    $3
)
ON CONFLICT (app_id, name) DO UPDATE SET
    branch_id = EXCLUDED.branch_id
`

type MigrateLegacyChannelParams struct {
	AppID    pgtype.UUID `json:"app_id"`
	BranchID *int64      `json:"branch_id"`
	Name     string      `json:"name"`
}

func (q *Queries) MigrateLegacyChannel(ctx context.Context, arg MigrateLegacyChannelParams) error {
	_, err := q.db.Exec(ctx, migrateLegacyChannel, arg.AppID, arg.BranchID, arg.Name)
	return err
}

const migrateLegacyRuntimeVersion = `-- name: MigrateLegacyRuntimeVersion :exec
INSERT INTO runtime_versions (
    app_id, 
    version, 
    created_at, 
    updated_at
) VALUES (
    $1, 
    $2, 
    $3, 
    $4
)
ON CONFLICT (app_id, version) DO UPDATE SET
    updated_at = EXCLUDED.updated_at
`

type MigrateLegacyRuntimeVersionParams struct {
	AppID     pgtype.UUID        `json:"app_id"`
	Version   string             `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MigrateLegacyRuntimeVersion(ctx context.Context, arg MigrateLegacyRuntimeVersionParams) error {
	_, err := q.db.Exec(ctx, migrateLegacyRuntimeVersion,
		arg.AppID,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const migrateLegacyUpdate = `-- name: MigrateLegacyUpdate :exec
INSERT INTO updates (
    id, 
    branch_id, 
    runtime_version_id, 
    update_type, 
    platform, 
    commit_hash, 
    message,
    checked_at,
    update_uuid,
    created_at
) VALUES (
    $1,
    (SELECT id FROM branches b WHERE b.app_id = $2 AND b.name = $3),
    (SELECT id FROM runtime_versions rv WHERE rv.app_id = $2 AND rv.version = $4),
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (branch_id, id) DO UPDATE SET
    runtime_version_id = EXCLUDED.runtime_version_id,
    update_type = EXCLUDED.update_type,
    platform = EXCLUDED.platform,
    commit_hash = EXCLUDED.commit_hash,
    message = EXCLUDED.message,
    checked_at = EXCLUDED.checked_at,
    update_uuid = EXCLUDED.update_uuid,
    created_at = EXCLUDED.created_at
`

type MigrateLegacyUpdateParams struct {
	ID         int64              `json:"id"`
	AppID      pgtype.UUID        `json:"app_id"`
	Name       string             `json:"name"`
	Version    string             `json:"version"`
	UpdateType int32              `json:"update_type"`
	Platform   string             `json:"platform"`
	CommitHash string             `json:"commit_hash"`
	Message    *string            `json:"message"`
	CheckedAt  pgtype.Timestamptz `json:"checked_at"`
	UpdateUuid pgtype.UUID        `json:"update_uuid"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) MigrateLegacyUpdate(ctx context.Context, arg MigrateLegacyUpdateParams) error {
	_, err := q.db.Exec(ctx, migrateLegacyUpdate,
		arg.ID,
		arg.AppID,
		arg.Name,
		arg.Version,
		arg.UpdateType,
		arg.Platform,
		arg.CommitHash,
		arg.Message,
		arg.CheckedAt,
		arg.UpdateUuid,
		arg.CreatedAt,
	)
	return err
}

const revokeApiKeyByID = `-- name: RevokeApiKeyByID :execresult
UPDATE api_keys
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = $1 AND app_id = $2
`

type RevokeApiKeyByIDParams struct {
	ID    int64       `json:"id"`
	AppID pgtype.UUID `json:"app_id"`
}

func (q *Queries) RevokeApiKeyByID(ctx context.Context, arg RevokeApiKeyByIDParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, revokeApiKeyByID, arg.ID, arg.AppID)
}

const storeUpdateUUID = `-- name: StoreUpdateUUID :execresult
UPDATE updates
SET update_uuid = $2
WHERE updates.id = $1 AND branch_id = (
    SELECT branches.id 
    FROM branches 
    WHERE app_id = $3 
      AND name = $4
)
`

type StoreUpdateUUIDParams struct {
	ID         int64       `json:"id"`
	UpdateUuid pgtype.UUID `json:"update_uuid"`
	AppID      pgtype.UUID `json:"app_id"`
	Name       string      `json:"name"`
}

func (q *Queries) StoreUpdateUUID(ctx context.Context, arg StoreUpdateUUIDParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, storeUpdateUUID,
		arg.ID,
		arg.UpdateUuid,
		arg.AppID,
		arg.Name,
	)
}

const updateAppNameByID = `-- name: UpdateAppNameByID :execresult
UPDATE apps 
SET name = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateAppNameByIDParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateAppNameByID(ctx context.Context, arg UpdateAppNameByIDParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateAppNameByID, arg.ID, arg.Name)
}

const updateChannelBranchMapping = `-- name: UpdateChannelBranchMapping :execresult
UPDATE channels
SET branch_id = $1
WHERE channels.app_id = $2
  AND channels.id = $3
  AND EXISTS (
      SELECT 1 FROM branches
      WHERE branches.id = $1 AND branches.app_id = $2
  )
`

type UpdateChannelBranchMappingParams struct {
	BranchID *int64      `json:"branch_id"`
	AppID    pgtype.UUID `json:"app_id"`
	ID       int64       `json:"id"`
}

// The EXISTS clause scopes the *target* branch to the caller's app. fk_channels_branch
// only references branches(id), so without it any tenant's branch id satisfies the FK.
func (q *Queries) UpdateChannelBranchMapping(ctx context.Context, arg UpdateChannelBranchMappingParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateChannelBranchMapping, arg.BranchID, arg.AppID, arg.ID)
}

const validateAndTouchAuth = `-- name: ValidateAndTouchAuth :one
UPDATE api_keys
SET last_used_at = CURRENT_TIMESTAMP
WHERE app_id = $1
  AND hashed_key = $2
  AND revoked_at IS NULL
RETURNING TRUE AS is_valid
`

type ValidateAndTouchAuthParams struct {
	AppID     pgtype.UUID `json:"app_id"`
	HashedKey string      `json:"hashed_key"`
}

func (q *Queries) ValidateAndTouchAuth(ctx context.Context, arg ValidateAndTouchAuthParams) (bool, error) {
	row := q.db.QueryRow(ctx, validateAndTouchAuth, arg.AppID, arg.HashedKey)
	var is_valid bool
	err := row.Scan(&is_valid)
	return is_valid, err
}
