name: Push workflow

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/axelmarciano/expo-open-ota-ci:latest
      credentials:
        username: axelmarciano
        password: ${{ secrets.DOCKER_GITHUB_CONTAINER_REGISTRY_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Check if .env exists or create it
        run: |
          if [ ! -f .env ]; then
            touch .env
          fi

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/.go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Install Go dependencies
        run: |
          go mod tidy 
          go mod download

      - name: Run tests
        run: make test_app html

      - name: Upload coverage artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.html
          retention-days: 1
